Repository imanujsharma99/Hacktoberfest_2021, pull requests merged in 2021-10, with the labels that each got.

#16 Create HelloJava.java
  Beginners/first/HelloJava.java
Labels: hacktoberfest-accepted

#20 Create RemoveDuplicatefromLinkedList.cpp
  Beginners/Some Basic C++ Programs/RemoveDuplicatefromLinkedList.cpp
Labels: hacktoberfest-accepted

#19 Create Merge2SortedArrays.cpp
  Beginners/Training/Merge2SortedArrays.cpp
Labels: hacktoberfest-accepted

#18 Create LuckyAliveInaCircle.cpp
  Beginners/Training/LuckyAliveInaCircle.cpp
Labels: hacktoberfest-accepted

#17 Create Rotateby90Degree.cpp
  Beginners/Training/Rotateby90Degree.cpp
Labels: hacktoberfest-accepted

#21 Create matrix
  Beginners/Some Basic C++ Programs/matrix
Labels: hacktoberfest-accepted

#22 Create Create Lexicographic rank of a string
  Beginners/Some Basic C++ Programs/Create Lexicographic rank of a string
Labels: hacktoberfest-accepted

#23 Create Create merge without space
  Beginners/Some Basic C++ Programs/Create merge without space
Labels: hacktoberfest-accepted

#24 Create Create median of 2 sorted array
  Beginners/Some Basic C++ Programs/Create median of 2 sorted array
Labels: hacktoberfest-accepted

#25 Create Merge_Two_Sorted_Lists.java
  Beginners/Training/Merge_Two_Sorted_Lists.java
Labels: hacktoberfest-accepted

#28 Created Fibonacci file with C++ without recursion
  Beginners/Some Basic C++ Programs/Fibonacci Series
Labels: hacktoberfest-accepted

#30 Create quick sort
  Beginners/Some Basic C++ Programs/quick sort
Labels: hacktoberfest-accepted

#29 Create merge sort
  Beginners/Some Basic C++ Programs/merge sort
Labels: hacktoberfest-accepted

#27 Create sum of array
  Beginners/Some Basic C++ Programs/sum  of array
Labels: hacktoberfest-accepted

#26 Create sorting of array
  Beginners/Some Basic C++ Programs/sorting of array
Labels: hacktoberfest-accepted

#34 Create delete node in double linked list
  Beginners/Some Basic C++ Programs/delete node in double linked list
Labels: good first issue, hacktoberfest-accepted

#32 Create design
  Beginners/Some Basic C++ Programs/design
Labels: hacktoberfest-accepted

#36 Create infix expression
  Beginners/Some Basic C++ Programs/infix expression
Labels: hacktoberfest-accepted

#35 Create infix to postfix
  Beginners/Some Basic C++ Programs/infix to postfix
Labels: hacktoberfest-accepted

#33 Create delete node in doubly linkedlist
  Beginners/Some Basic C++ Programs/delete node in doubly linkedlist
Labels: hacktoberfest-accepted

#31 Create patterns.cpp
  Beginners/Some Basic C++ Programs/patterns.cpp
Labels: hacktoberfest-accepted

#38 Create height of binary tree
  Beginners/Some Basic C++ Programs/height of binary tree
Labels: hacktoberfest-accepted

#37 Create depth of binary tree
  Beginners/Some Basic C++ Programs/depth of binary tree
Labels: hacktoberfest-accepted

#40 Create greedy algo
  Beginners/Some Basic C++ Programs/greedy algo
Labels: hacktoberfest-accepted

#39 Create huffman encoding
  Beginners/Some Basic C++ Programs/huffman encoding
Labels: hacktoberfest-accepted

#47 Pattern in java
  Pattern.java
  README .md
Labels: hacktoberfest-accepted

#46 Create rotate double linked list
  Beginners/Some Basic C++ Programs/rotate double linked list
Labels: hacktoberfest-accepted

#45 Create Rotate Doubly linked list by N nodes
  Beginners/Some Basic C++ Programs/Rotate Doubly linked list by N nodes
Labels: hacktoberfest-accepted

#44 Create reverse stack
  Beginners/Some Basic C++ Programs/reverse stack
Labels: hacktoberfest-accepted

#43 Create reverse stack using recursion
  Beginners/Some Basic C++ Programs/reverse stack using recursion
Labels: hacktoberfest-accepted

#42 Create Kruskal minimum spanning tree algo
  Beginners/Some Basic C++ Programs/Kruskal minimum spanning tree algo
Labels: hacktoberfest-accepted

#41 Create Kruskal’s Minimum Spanning Tree Algorithm Greedy algo
  Beginners/Some Basic C++ Programs/Kruskal’s Minimum Spanning Tree Algorithm Greedy algo
Labels: hacktoberfest-accepted

#49 Create bfs using stl
  Beginners/Some Basic C++ Programs/bfs using stl
Labels: hacktoberfest-accepted

#50 Create BFS using STL
  Beginners/Some Basic C++ Programs/BFS using STL
Labels: good first issue, hacktoberfest-accepted, Open-source

#51 Create BFs using STL
  Beginners/Some Basic C++ Programs/BFs using STL
Labels: hacktoberfest-accepted, Open-source

#52 Create BFS
  Beginners/Some Basic C++ Programs/BFS
Labels: hacktoberfest-accepted, Open-source

#48 Create BFS
  Beginners/Some Basic C++ Programs/BFS
Labels: hacktoberfest-accepted

#61 Create rat in maze
  Beginners/Some Basic C++ Programs/rat in maze
Labels: hacktoberfest-accepted

#60 Create Mouse in a maze
  Beginners/Some Basic C++ Program/Mouse in a maze
Labels: hacktoberfest-accepted

#62 Create rat in a maze
  Beginners/Some Basic C++ Programs/rat in a maze
Labels: hacktoberfest-accepted

#59 Create Rat in a Maze
  Beginners/Some Basic C++ Programs/Rat in a Maze
Labels: hacktoberfest-accepted

#58 Create Rat in a Maze
  Beginners/Some Basic C++ Programs/Rat in a Maze
Labels: hacktoberfest-accepted

#66 Create DFT
  Beginners/Some Basic C++ Programs/DFT
Labels: hacktoberfest-accepted

#65 Create DFS algo
  Beginners/Some Basic C++ Programs/DFS algo
Labels: hacktoberfest-accepted

#67 Create depth first traversal
  Beginners/Some Basic C++ Programs/depth first traversal
Labels: hacktoberfest-accepted

#54 Create transpose the graph
  Beginners/Some Basic C++ Programs/transpose the graph
Labels: hacktoberfest-accepted

#53 Create Transpose graph
  Beginners/Some Basic C++ Programs/Transpose graph
Labels: hacktoberfest-accepted

#64 Create Iterative df
  Beginners/Some Basic C++ Program/Iterative df
Labels: hacktoberfest-accepted

#63 Create Iterative Depth First Traversal of Graph
  Beginners/Some Basic C++ Programs/Iterative Depth First Traversal of Graph
Labels: hacktoberfest-accepted

#57 Create basic transpose graph
  Beginners/Some Basic C++ Programs/basic transpose graph
Labels: hacktoberfest-accepted

#55 Create Transpose graph
  Beginners/Some Basic C++ Programs/Transpose graph
Labels: hacktoberfest-accepted

#69 added some comments
  Beginners/Some Basic C++ Programs/DFS algo
Labels: hacktoberfest-accepted

#68 Create Palindrome-number.java
  Palindrome-number.java
Labels: hacktoberfest-accepted

#73 Create prog for FCFS scheduling algo
  Beginners/Some Basic C++ Programs/prog for FCFS scheduling algo
Labels: hacktoberfest-accepted

#72 Create program for priority scheduling algorithm
  Beginners/Some Basic C++ Programs/program for priority scheduling algorithm
Labels: hacktoberfest-accepted

#71 Create bubble sort in c++
  Beginners/Some Basic C++ Programs/bubble sort in c++
Labels: hacktoberfest-accepted

#74 Create C++ Program to Delete an Element from Array
  Beginners/Some Basic C++ Programs/C++ Program to Delete an Element from Array
Labels: hacktoberfest-accepted

#70 Create selection sort in c++
  Beginners/Some Basic C++ Programs/selection sort in c++
Labels: hacktoberfest-accepted
